# Generated by Django 4.2.7 on 2025-12-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikimap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='oldest_date',
            field=models.DateField(null=True),
        ),
    ]
